export const campaignData = [
  {
    id: "cmp-1",
    title: "Solar Mesh for Rural Clinics",
    founder: "Dr. Amara Okafor",
    category: "Health",
    description: "Deploy decentralized solar backups for underserved health centers to prevent power outages.",
    raised: 18500000,
    target: 25000000,
    daysRemaining: 18,
    rewardTiers: [
      { id: "cmp-1-t1", title: "Early Supporter", amount: 10000, benefit: "Thank You Badge + Impact Updates" },
      { id: "cmp-1-t2", title: "Growth Backer", amount: 50000, benefit: "Priority Access + Investor Webinar" },
      { id: "cmp-1-t3", title: "Equity Partner", amount: 200000, benefit: "2% Equity Token + Governance Rights" },
    ],
    story: {
      problem: "Rural clinics lose critical power during emergencies, disrupting diagnostics and care delivery.",
      solution: "We deploy modular solar-battery microgrids with IoT uptime monitoring and predictive maintenance.",
      market: "Over 9,000 clinics across West Africa need resilient energy infrastructure within five years.",
      roadmap: "Pilot 20 clinics, scale to 150 clinics, integrate insurance-backed uptime guarantees.",
      useOfFunds: "Hardware procurement, installer training, deployment operations, and uptime analytics.",
      team: "Energy engineers, healthcare operators, and compliance leads from distributed-grid startups.",
    },
    activity: [
      "21 new backers joined in the last 24 hours.",
      "Milestone unlocked: 70% deployment readiness.",
      "Founder update posted: Q2 procurement secured.",
    ],
    metrics: {
      backers: 3420,
      fundsDeployed: 12400000,
      projectsFunded: 27,
      countries: 6,
    },
  },
  {
    id: "cmp-2",
    title: "Smart Irrigation Chain",
    founder: "Tunde Balogun",
    category: "Agriculture",
    description: "Support IoT-powered irrigation with transparent farmer funding and yield reporting.",
    raised: 9200000,
    target: 15000000,
    daysRemaining: 27,
    rewardTiers: [
      { id: "cmp-2-t1", title: "Early Supporter", amount: 10000, benefit: "Thank You Badge + Yield Updates" },
      { id: "cmp-2-t2", title: "Growth Backer", amount: 50000, benefit: "Early Access + Farm Insights Webinar" },
      { id: "cmp-2-t3", title: "Equity Partner", amount: 200000, benefit: "2% Equity Token + Voting Rights" },
    ],
    story: {
      problem: "Smallholder farmers face low yields due to inconsistent water access and weak planning data.",
      solution: "Sensor-driven irrigation plans automate water cycles and tie fund usage to transparent crop metrics.",
      market: "Nigeria has over 35 million hectares of arable land with under-digitized irrigation operations.",
      roadmap: "Deploy 1,000 sensors, onboard 4 cooperatives, then expand to 12 states.",
      useOfFunds: "IoT hardware, farmer onboarding, cloud analytics, and local support teams.",
      team: "Agri-engineers, hardware specialists, and cooperative development managers.",
    },
    activity: [
      "New cooperative onboarded in Kaduna.",
      "Weekly report: 14% water efficiency gain.",
      "Backer AMA scheduled for Friday.",
    ],
    metrics: {
      backers: 2190,
      fundsDeployed: 6800000,
      projectsFunded: 15,
      countries: 4,
    },
  },
  {
    id: "cmp-3",
    title: "Community STEM Pods",
    founder: "Chinwe Nnadi",
    category: "Education",
    description: "Build modular learning labs that deliver robotics and coding classes to local communities.",
    raised: 6700000,
    target: 12000000,
    daysRemaining: 34,
    rewardTiers: [
      { id: "cmp-3-t1", title: "Early Supporter", amount: 10000, benefit: "Thank You Badge + Program Updates" },
      { id: "cmp-3-t2", title: "Growth Backer", amount: 50000, benefit: "Mentor Session + Early Demo Access" },
      { id: "cmp-3-t3", title: "Equity Partner", amount: 200000, benefit: "2% Equity Token + Governance Rights" },
    ],
    story: {
      problem: "Many communities lack practical STEM labs, limiting innovation pathways for youth.",
      solution: "Portable pods deliver maker equipment, curriculum, and remote mentorship in one deployable unit.",
      market: "Public and private schools seek scalable lab models with measurable outcomes and local relevance.",
      roadmap: "Launch 8 pods, measure outcomes, scale through regional education partnerships.",
      useOfFunds: "Lab hardware, facilitators, learning content, and operations.",
      team: "EdTech operators, STEM instructors, and curriculum designers.",
    },
    activity: [
      "Pilot cohort reached 500 learners.",
      "Partner school network expanded to 3 states.",
      "Monthly impact dashboard published.",
    ],
    metrics: {
      backers: 1540,
      fundsDeployed: 4900000,
      projectsFunded: 11,
      countries: 3,
    },
  },
  {
    id: "cmp-4",
    title: "ExaPay MSME Launchpad",
    founder: "Ibrahim Sule",
    category: "Technology",
    description: "Fund grants and tooling for early-stage fintech founders in emerging markets.",
    raised: 14200000,
    target: 20000000,
    daysRemaining: 9,
    rewardTiers: [
      { id: "cmp-4-t1", title: "Early Supporter", amount: 10000, benefit: "Thank You Badge + Founder Updates" },
      { id: "cmp-4-t2", title: "Growth Backer", amount: 50000, benefit: "Early Access + Demo Day Pass" },
      { id: "cmp-4-t3", title: "Equity Partner", amount: 200000, benefit: "2% Equity Token + Governance Rights" },
    ],
    story: {
      problem: "MSME fintech startups struggle to access patient, cross-border early-stage capital.",
      solution: "Launchpad combines milestone-based funding, product tooling credits, and mentor-backed support.",
      market: "Africa's MSME fintech segment is growing rapidly with demand for compliant payment rails.",
      roadmap: "Fund 25 startups, publish KPI dashboards, and establish cross-border merchant partnerships.",
      useOfFunds: "Founder grants, product infrastructure credits, and accelerator operations.",
      team: "Fintech founders, venture operators, and risk/compliance specialists.",
    },
    activity: [
      "4 startups reached payment pilot stage.",
      "New mentor cohort announced.",
      "KYC-complete pipeline now 38 startups.",
    ],
    metrics: {
      backers: 2890,
      fundsDeployed: 9300000,
      projectsFunded: 19,
      countries: 8,
    },
  },
];
