export const playerProfiles = [
  {
    id: "st-1",
    fullName: "Kofi Mensah",
    position: "Winger",
    age: 19,
    nationality: "Ghana",
    currentClub: "Accra Elite",
    jerseyNumber: 11,
    verified: true,
    overallRating: 92,
    walletAddress: "0x8a23be91f32d8c29a4f6eb70c2ad15b9e8ab12cd",
    nftMinted: true,
    stats: {
      matches: 28,
      goals: 14,
      assists: 9,
      cleanSheets: 0,
      yellowCards: 3,
      redCards: 0,
      minutesPlayed: 2360,
    },
    ai: {
      speed: 91,
      strength: 82,
      stamina: 89,
      tactical: 87,
      growthPotential: 93,
      rankingScore: 95,
    },
    bio: {
      background: "Raised in Kumasi, Kofi progressed through local youth academies before earning a professional debut at 17.",
      style: "Explosive wide attacker with high transition threat, diagonal runs, and progressive ball carrying.",
      achievements: ["U20 National Team Selection", "League Young Player Nominee", "Top 5 U20 Assists"],
    },
    career: [
      { year: "2022", club: "Accra Elite U19", appearances: 18, goals: 6, achievements: "Academy MVP" },
      { year: "2023", club: "Accra Elite B", appearances: 22, goals: 9, achievements: "Promotion Starter" },
      { year: "2024", club: "Accra Elite", appearances: 28, goals: 14, achievements: "Team of the Month x2" },
    ],
  },
  {
    id: "st-2",
    fullName: "Amina Yusuf",
    position: "Striker",
    age: 18,
    nationality: "Nigeria",
    currentClub: "Lagos Stars",
    jerseyNumber: 9,
    verified: true,
    overallRating: 89,
    walletAddress: "0x9b10fce1a65d7f22ba9f7d4191d71ebf64bc8a0e",
    nftMinted: true,
    stats: {
      matches: 24,
      goals: 17,
      assists: 5,
      cleanSheets: 0,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 2012,
    },
    ai: {
      speed: 88,
      strength: 79,
      stamina: 85,
      tactical: 84,
      growthPotential: 91,
      rankingScore: 92,
    },
    bio: {
      background: "Amina emerged from Lagos community leagues and became one of the fastest-rising youth forwards in the region.",
      style: "Clinical finisher, aggressive pressing profile, and intelligent off-ball movement in the final third.",
      achievements: ["Golden Boot Finalist", "League Player of the Week x4", "Youth Cup Winner"],
    },
    career: [
      { year: "2022", club: "Lagos Stars U17", appearances: 14, goals: 8, achievements: "Top Youth Scorer" },
      { year: "2023", club: "Lagos Stars U19", appearances: 20, goals: 13, achievements: "Cup Final Winner" },
      { year: "2024", club: "Lagos Stars", appearances: 24, goals: 17, achievements: "Senior Breakout Season" },
    ],
  },
  {
    id: "st-3",
    fullName: "Lina Haddad",
    position: "Midfielder",
    age: 20,
    nationality: "Morocco",
    currentClub: "Rabat United",
    jerseyNumber: 8,
    verified: true,
    overallRating: 90,
    walletAddress: "0xf31b6d2a5ce8b1378af63f2d0a194f2d7ab9c3ef",
    nftMinted: true,
    stats: {
      matches: 31,
      goals: 11,
      assists: 12,
      cleanSheets: 0,
      yellowCards: 4,
      redCards: 0,
      minutesPlayed: 2648,
    },
    ai: {
      speed: 84,
      strength: 80,
      stamina: 92,
      tactical: 91,
      growthPotential: 90,
      rankingScore: 93,
    },
    bio: {
      background: "Lina is a technically refined midfielder from Rabat's development circuit with leadership traits and high game IQ.",
      style: "Tempo controller, line-breaking passer, and ball-winner with elite spatial awareness.",
      achievements: ["Regional Midfield MVP", "Top Assist Provider", "Captain - Youth National Camp"],
    },
    career: [
      { year: "2021", club: "Rabat Academy", appearances: 19, goals: 4, achievements: "Youth Captain" },
      { year: "2023", club: "Rabat United B", appearances: 26, goals: 8, achievements: "Promotion Playoffs" },
      { year: "2024", club: "Rabat United", appearances: 31, goals: 11, achievements: "Assist Leader" },
    ],
  },
  {
    id: "st-4",
    fullName: "Diego Alvarez",
    position: "Midfielder",
    age: 20,
    nationality: "Colombia",
    currentClub: "Bogota Prime",
    jerseyNumber: 6,
    verified: false,
    overallRating: 86,
    walletAddress: "0xd02af7bd44e1c89f59a1c8a2d09e5b3bc4f0de22",
    nftMinted: false,
    stats: {
      matches: 26,
      goals: 8,
      assists: 7,
      cleanSheets: 0,
      yellowCards: 5,
      redCards: 1,
      minutesPlayed: 2280,
    },
    ai: {
      speed: 80,
      strength: 78,
      stamina: 84,
      tactical: 83,
      growthPotential: 87,
      rankingScore: 88,
    },
    bio: {
      background: "Developed through Bogota grassroots football, Diego combines composure and physicality in central midfield roles.",
      style: "Box-to-box presence with strong recoveries and short-range progression play.",
      achievements: ["Intercity Cup Finalist", "Top Tackles in Club", "Emerging Talent Nominee"],
    },
    career: [
      { year: "2022", club: "Bogota Prime U19", appearances: 17, goals: 3, achievements: "Rookie of the Season" },
      { year: "2023", club: "Bogota Prime B", appearances: 21, goals: 6, achievements: "Defensive Midfield Starter" },
      { year: "2024", club: "Bogota Prime", appearances: 26, goals: 8, achievements: "Senior Promotion" },
    ],
  },
  {
    id: "st-5",
    fullName: "Samuel Osei",
    position: "Goalkeeper",
    age: 21,
    nationality: "Ghana",
    currentClub: "Kumasi FC",
    jerseyNumber: 1,
    verified: false,
    overallRating: 88,
    walletAddress: "0xbdb3e517fc2a5a6f2bda73c9420f8e6bd9a0f123",
    nftMinted: false,
    stats: {
      matches: 30,
      goals: 0,
      assists: 1,
      cleanSheets: 12,
      yellowCards: 2,
      redCards: 0,
      minutesPlayed: 2700,
    },
    ai: {
      speed: 74,
      strength: 86,
      stamina: 90,
      tactical: 88,
      growthPotential: 89,
      rankingScore: 90,
    },
    bio: {
      background: "Samuel rose through Kumasi's academy structure and is recognized for consistency in high-pressure matches.",
      style: "Commanding goalkeeper with strong aerial control and excellent shot-stopping reflexes.",
      achievements: ["Top Clean Sheets", "Goalkeeper of the Month x3", "Cup Semi-final Hero"],
    },
    career: [
      { year: "2021", club: "Kumasi FC U19", appearances: 15, goals: 0, achievements: "Academy Best Keeper" },
      { year: "2023", club: "Kumasi FC B", appearances: 24, goals: 0, achievements: "Consecutive Clean Sheets Record" },
      { year: "2024", club: "Kumasi FC", appearances: 30, goals: 0, achievements: "Senior First Choice GK" },
    ],
  },
  {
    id: "st-6",
    fullName: "Asha Kimani",
    position: "Sprinter",
    age: 20,
    nationality: "Kenya",
    currentClub: "Nairobi Sprint Lab",
    jerseyNumber: 7,
    verified: true,
    overallRating: 87,
    walletAddress: "0xca27f9de1a92c5e8d2ab06fca1d57f2bd3ec9a48",
    nftMinted: true,
    stats: {
      matches: 18,
      goals: 0,
      assists: 0,
      cleanSheets: 0,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 0,
    },
    ai: {
      speed: 93,
      strength: 77,
      stamina: 88,
      tactical: 79,
      growthPotential: 92,
      rankingScore: 91,
    },
    bio: {
      background: "Asha transitioned from school athletics to professional sprint circuits and has rapidly improved race consistency.",
      style: "Explosive short-distance acceleration with elite split times and strong biomechanical efficiency.",
      achievements: ["Regional 100m Bronze", "National Trial Finalist", "Training Camp Scholarship"],
    },
    career: [
      { year: "2022", club: "Nairobi Youth Track", appearances: 10, goals: 0, achievements: "Junior Sprint Champion" },
      { year: "2023", club: "Kenya Elite Development", appearances: 14, goals: 0, achievements: "Top Split Time Award" },
      { year: "2024", club: "Nairobi Sprint Lab", appearances: 18, goals: 0, achievements: "Performance Contract Secured" },
    ],
  },
];

