<?php

return [
    'cache_store' => env('GIFTCARD_RATE_CACHE_STORE', env('CACHE_STORE', 'database')),
    'rate_ttl_seconds' => (int) env('GIFTCARD_RATE_TTL_SECONDS', 45),
    'lock_duration_seconds' => (int) env('GIFTCARD_RATE_LOCK_SECONDS', 60),
    'max_volatility_pct' => (float) env('GIFTCARD_RATE_MAX_VOLATILITY_PCT', 0.035),
    'default_min_profit_margin' => (float) env('GIFTCARD_MIN_PROFIT_MARGIN', 0.045),
    'competitive_band_pct' => (float) env('GIFTCARD_COMPETITIVE_BAND_PCT', 0.025),

    'brands' => [
        'amazon' => [
            'label' => 'Amazon',
            'market_buy_rate' => 785.00,
            'market_sell_rate' => 930.00,
            'fallback_buy_rate' => 760.00,
            'fallback_sell_rate' => 900.00,
            'min_profit_margin' => 0.05,
            'inventory_level' => 0.58,
            'demand_level' => 0.82,
            'min_threshold' => 0.25,
            'max_threshold' => 0.82,
            'external_buy_rate' => 905.00,
            'external_sell_rate' => 835.00,
        ],
        'steam' => [
            'label' => 'Steam',
            'market_buy_rate' => 745.00,
            'market_sell_rate' => 900.00,
            'fallback_buy_rate' => 720.00,
            'fallback_sell_rate' => 875.00,
            'min_profit_margin' => 0.055,
            'inventory_level' => 0.36,
            'demand_level' => 0.66,
            'min_threshold' => 0.30,
            'max_threshold' => 0.78,
            'external_buy_rate' => 875.00,
            'external_sell_rate' => 790.00,
        ],
        'itunes' => [
            'label' => 'iTunes',
            'market_buy_rate' => 725.00,
            'market_sell_rate' => 885.00,
            'fallback_buy_rate' => 700.00,
            'fallback_sell_rate' => 860.00,
            'min_profit_margin' => 0.06,
            'inventory_level' => 0.70,
            'demand_level' => 0.52,
            'min_threshold' => 0.28,
            'max_threshold' => 0.80,
            'external_buy_rate' => 850.00,
            'external_sell_rate' => 780.00,
        ],
        'google_play' => [
            'label' => 'Google Play',
            'market_buy_rate' => 735.00,
            'market_sell_rate' => 895.00,
            'fallback_buy_rate' => 710.00,
            'fallback_sell_rate' => 870.00,
            'min_profit_margin' => 0.055,
            'inventory_level' => 0.48,
            'demand_level' => 0.74,
            'min_threshold' => 0.25,
            'max_threshold' => 0.78,
            'external_buy_rate' => 865.00,
            'external_sell_rate' => 795.00,
        ],
        'apple' => [
            'label' => 'Apple',
            'market_buy_rate' => 750.00,
            'market_sell_rate' => 910.00,
            'fallback_buy_rate' => 725.00,
            'fallback_sell_rate' => 885.00,
            'min_profit_margin' => 0.055,
            'inventory_level' => 0.44,
            'demand_level' => 0.76,
            'min_threshold' => 0.30,
            'max_threshold' => 0.82,
            'external_buy_rate' => 880.00,
            'external_sell_rate' => 805.00,
        ],
    ],
];
