import {
  Activity,
  BadgeDollarSign,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  CandlestickChart,
  CircleDollarSign,
  FileCheck2,
  FileText,
  Gift,
  Landmark,
  LayoutDashboard,
  ListChecks,
  Lock,
  Medal,
  Settings,
  Shield,
  ShoppingBag,
  Sprout,
  Ticket,
  UserCog,
  Users,
  Wallet,
} from "lucide-react";

export const adminMenu = [
  { key: "dashboard", label: "Dashboard", icon: LayoutDashboard, permissions: ["dashboard.view"] },
  { key: "users", label: "Users", icon: Users, permissions: ["users.view"] },
  { key: "wallets", label: "Wallets", icon: Wallet, permissions: ["wallets.view"] },
  { key: "transactions", label: "Transactions", icon: Activity, permissions: ["transactions.view"] },
  { key: "trading", label: "Trading", icon: CandlestickChart, permissions: ["trade.manage"] },
  { key: "p2p", label: "P2P", icon: BriefcaseBusiness, permissions: ["trade.manage"] },
  { key: "staking", label: "Staking", icon: CircleDollarSign, permissions: ["staking.manage"] },
  { key: "rewards", label: "Rewards", icon: Gift, permissions: ["reward.manage"] },
  { key: "nft", label: "NFT", icon: Medal, permissions: ["nft.manage"] },
  { key: "agritech", label: "AgriTech", icon: Sprout, permissions: ["agri.manage"] },
  { key: "sports", label: "Sports Pool", icon: BadgeDollarSign, permissions: ["sports.manage"] },
  { key: "edtech", label: "EdTech", icon: BookOpen, permissions: ["edtech.manage"] },
  { key: "crowdfunding", label: "Crowdfunding", icon: Landmark, permissions: ["crowdfunding.manage"] },
  { key: "lottery", label: "Lottery", icon: Ticket, permissions: ["lottery.manage"] },
  { key: "giftcard", label: "Giftcard", icon: ShoppingBag, permissions: ["giftcard.manage"] },
  { key: "campaigns", label: "Campaigns", icon: Bell, permissions: ["campaign.manage"] },
  { key: "kyc", label: "KYC", icon: FileCheck2, permissions: ["kyc.review"] },
  { key: "treasury", label: "Treasury", icon: Landmark, permissions: ["treasury.manage"] },
  { key: "notifications", label: "Notifications", icon: Bell, permissions: ["notifications.send"] },
  { key: "logs", label: "Logs", icon: FileText, permissions: ["logs.view"] },
  { key: "security", label: "Security", icon: Shield, permissions: ["security.view"] },
  { key: "admins", label: "Admins", icon: UserCog, permissions: ["admins.manage"] },
  { key: "roles", label: "Roles", icon: ListChecks, permissions: ["roles.manage"] },
  { key: "permissions", label: "Permissions", icon: Lock, permissions: ["roles.manage"] },
  { key: "settings", label: "Settings", icon: Settings, permissions: ["settings.manage"] },
  { key: "system-monitor", label: "System Monitor", icon: Activity, permissions: ["system.view"] },
];
