<?php

declare(strict_types=1);

return [
    'permissions' => [
        'users.view',
        'users.edit',
        'wallet.view',
        'wallet.adjust',
        'trade.manage',
        'reward.manage',
        'staking.view',
        'staking.manage_assets',
        'staking.manage_products',
        'staking.manage_networks',
        'staking.manage_validators',
        'staking.manage_wallets',
        'staking.manage_delegations',
        'staking.approve_native_rewards',
        'staking.manage_exatoken_campaigns',
        'staking.fund_exatoken_reserve',
        'staking.approve_exatoken_rewards',
        'staking.manage_mainnet_activation',
        'staking.manage_rpc',
        'staking.reconcile',
        'staking.pause',
        'staking.export',
        'staking.audit',
        'nft.manage',
        'agri.manage',
        'sports.manage',
        'edtech.manage',
        'crowdfunding.manage',
        'lottery.manage',
        'giftcard.manage',
        'campaign.manage',
        'treasury.manage',
        'logs.view',
        'settings.manage',
        'admins.manage',
        'roles.manage',
        'notifications.send',
        'security.manage',
    ],

    'role_permissions' => [
        'super_admin' => ['*'],
        'admin' => [
            'users.view',
            'users.edit',
            'wallet.view',
            'wallet.adjust',
            'trade.manage',
            'reward.manage',
            'staking.view',
            'staking.manage_assets',
            'staking.manage_products',
            'staking.manage_networks',
            'staking.manage_validators',
            'staking.manage_wallets',
            'staking.manage_delegations',
            'staking.approve_native_rewards',
            'staking.manage_exatoken_campaigns',
            'staking.fund_exatoken_reserve',
            'staking.approve_exatoken_rewards',
            'staking.manage_mainnet_activation',
            'staking.manage_rpc',
            'staking.reconcile',
            'staking.pause',
            'staking.export',
            'staking.audit',
            'nft.manage',
            'agri.manage',
            'sports.manage',
            'edtech.manage',
            'crowdfunding.manage',
            'lottery.manage',
            'giftcard.manage',
            'campaign.manage',
            'treasury.manage',
            'logs.view',
            'settings.manage',
            'notifications.send',
            'security.manage',
        ],
        'moderator' => [
            'users.view',
            'giftcard.manage',
            'campaign.manage',
            'sports.manage',
            'logs.view',
            'notifications.send',
        ],
        'support' => [
            'users.view',
            'wallet.view',
            'logs.view',
            'notifications.send',
        ],
    ],

    'default_super_admin' => [
        'name' => env('ADMIN_SUPER_NAME', 'ExaEarn Super Admin'),
        'email' => env('ADMIN_SUPER_EMAIL', 'admin@exaearn.local'),
        'password' => env('ADMIN_SUPER_PASSWORD', 'ChangeMe123!'),
    ],
];
